// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIUNo2MO_BWPc5OrAoK7nzt3iIwLP2q-c',
    appId: '1:554289812342:web:1210744b2d7cacde2b2057',
    messagingSenderId: '554289812342',
    projectId: 'newsapp-6d008',
    authDomain: 'newsapp-6d008.firebaseapp.com',
    storageBucket: 'newsapp-6d008.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASHWagsxvVEi8qMnWg516x4UL8TXeuTvA',
    appId: '1:554289812342:android:5a48a582cf543c512b2057',
    messagingSenderId: '554289812342',
    projectId: 'newsapp-6d008',
    storageBucket: 'newsapp-6d008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALxm2miFozbGSSxFs63sLFIDXimIKC-ck',
    appId: '1:554289812342:ios:f9308faabf67256a2b2057',
    messagingSenderId: '554289812342',
    projectId: 'newsapp-6d008',
    storageBucket: 'newsapp-6d008.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALxm2miFozbGSSxFs63sLFIDXimIKC-ck',
    appId: '1:554289812342:ios:f9308faabf67256a2b2057',
    messagingSenderId: '554289812342',
    projectId: 'newsapp-6d008',
    storageBucket: 'newsapp-6d008.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIUNo2MO_BWPc5OrAoK7nzt3iIwLP2q-c',
    appId: '1:554289812342:web:f228faba02e82b142b2057',
    messagingSenderId: '554289812342',
    projectId: 'newsapp-6d008',
    authDomain: 'newsapp-6d008.firebaseapp.com',
    storageBucket: 'newsapp-6d008.firebasestorage.app',
  );
}
